/**
 * GENERATED FILE — do not edit.
 *
 * Produced from the backend's OpenAPI schema by scripts/generate-api-types.sh (DEV-2).
 * Regenerate with `npm run generate:api` after changing a DTO in the backend.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/evidence/{publicId}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upload State */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    publicId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadStateDto"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Append Chunk */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Upload-Offset": string | null;
                };
                path: {
                    publicId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expiry-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings expiring within the lead window, by impact on next assignment (§5.4) */
        get: {
            parameters: {
                query: {
                    leadDays: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpiryAlertDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partnerships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partnerships visible to the caller (§3 scoping) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnershipDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partnerships/{abbrev}/crew-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A partnership's swing calendar, oldest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    abbrev: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CrewChangeDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People visible to the caller (§3 scoping) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One person */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    personId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonDto"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{personId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A person's assignment history, most recent first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    personId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignmentDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{personId}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One person's evaluation against a swing (§5.2) */
        get: {
            parameters: {
                query: {
                    cc: string;
                    matrixVersionId: number | null;
                    partnership: string;
                };
                header?: never;
                path: {
                    personId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonEvaluationDto"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{personId}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A person's qualification holdings, by category then requirement code */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    personId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HoldingDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{personId}/holdings/{requirementId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set a person's holding for a requirement — audited (§4.3, AUTH-3) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    personId: number;
                    requirementId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetHoldingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HoldingDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{personId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A person's leave records, most recent first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    personId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaveRecordDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crew positions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PositionDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The requirement catalogue, retired entries included */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RequirementDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current actor, their roles, and the server's business date */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionDto"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The position slot model, by slot reference */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SlotDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swings/{partnership}/{cc}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whole-swing compliance evaluation (§5.3) */
        get: {
            parameters: {
                query: {
                    matrixVersionId: number | null;
                };
                header?: never;
                path: {
                    cc: string;
                    partnership: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SwingEvaluationDto"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swings/{partnership}/{cc}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gap report: every non-ok/na cell, ordered as a worklist (§5.4) */
        get: {
            parameters: {
                query: {
                    matrixVersionId: number | null;
                };
                header?: never;
                path: {
                    cc: string;
                    partnership: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GapReportRowDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swings/{partnership}/{cc}/quotas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quota rule evaluation for a swing, per shift where scoped (§5.3) */
        get: {
            parameters: {
                query: {
                    matrixVersionId: number | null;
                };
                header?: never;
                path: {
                    cc: string;
                    partnership: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuotaDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swings/{partnership}/{cc}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked crew suggestions for an open slot (§5.4) */
        get: {
            parameters: {
                query: {
                    limit: number;
                    slotRef: number;
                };
                header?: never;
                path: {
                    cc: string;
                    partnership: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuggestionDto"][];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delta */
        get: {
            parameters: {
                query: {
                    cursor: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncDeltaDto"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncQueueRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncQueueResultDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncSnapshotDto"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignmentDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            personId: number;
            /** Format: int64 */
            crewChangeId: number;
            ccId: string;
            partnershipAbbrev: string;
            /** Format: int32 */
            slotRef: number;
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
        };
        AssignmentEvaluationDto: {
            /** Format: int64 */
            assignmentId: number;
            /** Format: int64 */
            personId: number;
            sam: string;
            name: string;
            /** Format: int32 */
            slotRef: number;
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
            evaluation: components["schemas"]["PersonEvaluationDto"];
        };
        CellDto: {
            /** Format: int64 */
            requirementId: number;
            level: string;
            state: string;
            expiry: components["schemas"]["LocalDate"] | null;
            notes: string[];
            registerRecordId: string | null;
        };
        CrewChangeDto: {
            /** Format: int64 */
            id: number;
            ccId: string;
            /** Format: int64 */
            partnershipId: number;
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
            cutoff: components["schemas"]["LocalDate"];
        };
        EvidenceSubmissionDto: {
            publicId: components["schemas"]["UUID"];
            /** Format: int64 */
            requirementHintId: number | null;
            source: string;
            contentType: string | null;
            /** Format: int64 */
            declaredSize: number | null;
            /** Format: int64 */
            uploadOffset: number;
            uploadComplete: boolean;
            verificationStatus: string;
            rejectionReason: string | null;
            submittedAt: components["schemas"]["Instant"];
        };
        EvidenceSubmitDto: {
            publicId: components["schemas"]["UUID"];
            source: string;
            contentType?: string | null;
            /** Format: int64 */
            declaredSize?: number | null;
            declaredSha256?: string | null;
            /** Format: int64 */
            requirementHintId?: number | null;
        };
        ExpiryAlertDto: {
            /** Format: int64 */
            personId: number;
            sam: string;
            name: string;
            /** Format: int64 */
            requirementId: number;
            expiry: components["schemas"]["LocalDate"];
            /** Format: int64 */
            daysRemaining: number;
            impact: string;
        };
        GapReportRowDto: {
            /** Format: int64 */
            personId: number;
            sam: string;
            name: string;
            /** Format: int32 */
            slotRef: number;
            /** Format: int64 */
            assignmentId: number;
            /** Format: int64 */
            requirementId: number;
            level: string;
            state: string;
            expiry: components["schemas"]["LocalDate"] | null;
            registerRecordId: string | null;
            notes: string[];
        };
        HoldingDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            personId: number;
            /** Format: int64 */
            requirementId: number;
            status: string;
            expiry: components["schemas"]["LocalDate"] | null;
            issueDate: components["schemas"]["LocalDate"] | null;
            note: string | null;
        };
        /**
         * Format: date-time
         * @example 2022-03-10T16:15:50Z
         */
        Instant: string;
        LeaveRecordDto: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            personId: number;
            kind: string;
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
            status: string;
        };
        /**
         * Format: date
         * @example 2022-03-10
         */
        LocalDate: string;
        NotificationDto: {
            /** Format: int64 */
            id: number;
            kind: string;
            title: string;
            body: string | null;
            deepLink: string | null;
            createdAt: components["schemas"]["Instant"];
            readAt: components["schemas"]["Instant"] | null;
        };
        OpenSlotDto: {
            /** Format: int32 */
            ref: number;
            shift: string;
            allowedPositionIds: number[];
        };
        PartnershipDto: {
            /** Format: int64 */
            id: number;
            abbrev: string;
            name: string;
            vesselClass: string | null;
        };
        PersonDto: {
            /** Format: int64 */
            id: number;
            sam: string;
            name: string;
            /** Format: int64 */
            positionId: number;
            positionName: string;
            tier: string | null;
            /** Format: int64 */
            partnershipId: number;
            partnershipAbbrev: string;
            status: string;
            email: string | null;
        };
        PersonEvaluationDto: {
            /** Format: int64 */
            personId: number;
            rollUp: string;
            cells: components["schemas"]["CellDto"][];
        };
        PositionDto: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        QuotaDto: {
            footnote: string;
            /** Format: int64 */
            requirementId: number;
            scope: string;
            shift: string | null;
            /** Format: int32 */
            min: number;
            /** Format: int32 */
            actual: number;
            satisfied: boolean;
            /** Format: int32 */
            shortfall: number;
        };
        RequirementDto: {
            /** Format: int64 */
            id: number;
            code: string;
            category: string;
            title: string;
            status: string;
            issuingAuthority: string | null;
        };
        SessionDto: {
            label: string;
            roles: string[];
            /** Format: int64 */
            personId: number | null;
            partnershipIds: number[];
            today: components["schemas"]["LocalDate"];
            dateOverridden: boolean;
        };
        SetHoldingRequest: {
            status: string;
            expiry?: components["schemas"]["LocalDate"] | null;
            issueDate?: components["schemas"]["LocalDate"] | null;
            note?: string | null;
        };
        SlotDto: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            ref: number;
            shift: string;
            allowedPositionIds: number[];
            notes: string | null;
        };
        SuggestionDto: {
            /** Format: int64 */
            personId: number;
            sam: string;
            name: string;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            gapCount: number;
            /** Format: int32 */
            unknownCount: number;
            /** Format: int32 */
            expiringCount: number;
            crossPartnership: boolean;
            clash: boolean;
            reasons: string[];
        };
        SwingEvaluationDto: {
            ccId: string;
            /** Format: int64 */
            partnershipId: number;
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
            cutoff: components["schemas"]["LocalDate"];
            assignments: components["schemas"]["AssignmentEvaluationDto"][];
            openSlots: components["schemas"]["OpenSlotDto"][];
            partiallyCoveredSlots: components["schemas"]["OpenSlotDto"][];
            stateCounts: {
                [key: string]: number;
            };
            quotas: components["schemas"]["QuotaDto"][];
        };
        SyncDeltaDto: {
            /** Format: int64 */
            cursor: number;
            /** Format: int64 */
            referenceCursor: number;
            referenceStale: boolean;
            serverToday: components["schemas"]["LocalDate"];
            person: components["schemas"]["PersonDto"] | null;
            holdings: components["schemas"]["HoldingDto"][];
            assignments: components["schemas"]["AssignmentDto"][];
            leave: components["schemas"]["LeaveRecordDto"][];
            notifications: components["schemas"]["NotificationDto"][];
            submissions: components["schemas"]["EvidenceSubmissionDto"][];
            tombstones: components["schemas"]["SyncTombstoneDto"][];
            standing: components["schemas"]["SyncStandingDto"] | null;
        };
        SyncOperationDto: {
            opId: string;
            type: string;
            /** Format: int64 */
            notificationId?: number | null;
            readAt?: components["schemas"]["Instant"] | null;
            submission?: components["schemas"]["EvidenceSubmitDto"] | null;
        };
        SyncOperationResultDto: {
            opId: string;
            status: string;
            detail?: string | null;
            /** Format: int64 */
            uploadOffset?: number | null;
        };
        SyncQueueRequest: {
            operations: components["schemas"]["SyncOperationDto"][];
        };
        SyncQueueResultDto: {
            /** Format: int64 */
            cursor: number;
            results: components["schemas"]["SyncOperationResultDto"][];
        };
        SyncReferenceDto: {
            /** Format: int64 */
            cursor: number;
            /** Format: int64 */
            matrixVersionId: number | null;
            matrixVersionLabel: string | null;
            requirements: components["schemas"]["RequirementDto"][];
            positions: components["schemas"]["PositionDto"][];
            partnerships: components["schemas"]["PartnershipDto"][];
            crewChanges: components["schemas"]["CrewChangeDto"][];
        };
        SyncSnapshotDto: {
            /** Format: int64 */
            cursor: number;
            /** Format: int64 */
            referenceCursor: number;
            serverToday: components["schemas"]["LocalDate"];
            person: components["schemas"]["PersonDto"];
            holdings: components["schemas"]["HoldingDto"][];
            assignments: components["schemas"]["AssignmentDto"][];
            leave: components["schemas"]["LeaveRecordDto"][];
            notifications: components["schemas"]["NotificationDto"][];
            submissions: components["schemas"]["EvidenceSubmissionDto"][];
            reference: components["schemas"]["SyncReferenceDto"];
            standing: components["schemas"]["SyncStandingDto"] | null;
        };
        SyncStandingDto: {
            ccId: string;
            partnershipAbbrev: string;
            from: components["schemas"]["LocalDate"];
            to: components["schemas"]["LocalDate"];
            current: boolean;
            evaluation: components["schemas"]["PersonEvaluationDto"];
        };
        SyncTombstoneDto: {
            entityType: string;
            /** Format: int64 */
            entityId: number;
            /** Format: int64 */
            seq: number;
        };
        /** Format: uuid */
        UUID: string;
        UploadStateDto: {
            /** Format: int64 */
            offset: number;
            complete: boolean;
            /** Format: int64 */
            declaredSize: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
